-- 12345678
-- How to grant a user all access on a database without allowing him to delete the DB --

CREATE USER pgtest WITH PASSWORD '12345678';

GRANT ALL PRIVILEGES ON DATABASE testdb TO pgtest;

\c testdb

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA <schema_name> TO pgtest;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA <schema_name> TO pgtest;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA <schema_name> TO pgtest;

ALTER DEFAULT PRIVILEGES IN SCHEMA <schema_name> GRANT ALL PRIVILEGES ON TABLES TO pgtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA <schema_name> GRANT ALL PRIVILEGES ON SEQUENCES TO pgtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA <schema_name> GRANT ALL PRIVILEGES ON FUNCTIONS TO pgtest;


--------------------------------------------------------------------------------------



GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA locdba TO pgtest;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA locdba TO pgtest;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA locdba TO pgtest;

ALTER DEFAULT PRIVILEGES IN SCHEMA locdba GRANT ALL PRIVILEGES ON TABLES TO pgtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA locdba GRANT ALL PRIVILEGES ON SEQUENCES TO pgtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA locdba GRANT ALL PRIVILEGES ON FUNCTIONS TO pgtest;








GRANT ALL PRIVILEGES ON DATABASE testdb TO pgtest;

\c testdb

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA locdba TO pgtest;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA locdba TO pgtest;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA locdba TO pgtest;

ALTER DEFAULT PRIVILEGES IN SCHEMA locdba GRANT ALL PRIVILEGES ON TABLES TO pgtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA locdba GRANT ALL PRIVILEGES ON SEQUENCES TO pgtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA locdba GRANT ALL PRIVILEGES ON FUNCTIONS TO pgtest;
