














-- Grant on All Sequences in Schema
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auddba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bmdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA findba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hrdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA impdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA invdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA isodba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA locdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA mdmdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA qbedba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA qmsdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sdedba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA suitedba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA techdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA usmdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA vlpdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA webdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA wfmdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ssdx_eng TO pgdba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ssdx_tmp TO pgdba;

-- Grant USAGE on all newly created sequences in each schema
ALTER DEFAULT PRIVILEGES IN SCHEMA auddba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA bmdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA findba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA hrdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA impdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA invdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA isodba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA locdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA mdmdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA qbedba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA qmsdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA sdedba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA suitedba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA techdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA usmdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA vlpdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA webdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA wfmdba GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA ssdx_eng GRANT USAGE ON SEQUENCES TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA ssdx_tmp GRANT USAGE ON SEQUENCES TO pgdba;

---------------------------------------------------------------------------

-- in All Functions in Schema
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA auddba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA bmdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA findba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA hrdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA impdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA invdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA isodba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA locdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA mdmdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA qbedba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA qmsdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA sdedba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA suitedba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA techdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA usmdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA vlpdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA webdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA wfmdba TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA ssdx_eng TO pgdba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA ssdx_tmp TO pgdba;

-- Grant EXECUTE on all newly created functions and procedures in each schema
ALTER DEFAULT PRIVILEGES IN SCHEMA auddba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA bmdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA findba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA hrdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA impdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA invdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA isodba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA locdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA mdmdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA qbedba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA qmsdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA sdedba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA suitedba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA techdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA usmdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA vlpdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA webdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA wfmdba GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA ssdx_eng GRANT EXECUTE ON FUNCTIONS TO pgdba;
ALTER DEFAULT PRIVILEGES IN SCHEMA ssdx_tmp GRANT EXECUTE ON FUNCTIONS TO pgdba;

=================================================================================

-- Change Owner / Create Grants

=================================================================================


clean_multimedia_bck.sql




-- Grant USAGE on existing schemas
DO $$
DECLARE
    schema_record RECORD;
BEGIN
    -- Loop through all schemas excluding system schemas
    FOR schema_record IN
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
    LOOP
        -- Grant USAGE on the schema to pgdba
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO pgdba;', schema_record.schema_name);
    END LOOP;
END
$$;

-- Alter default privileges to grant USAGE on new objects
DO $$
DECLARE
    schema_record RECORD;
BEGIN
    -- Loop through all schemas excluding system schemas
    FOR schema_record IN
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
    LOOP
        -- Alter default privileges to grant USAGE on objects created in each schema
        EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT USAGE ON SCHEMAS TO pgdba;', schema_record.schema_name);
    END LOOP;
END
$$;




DO $$
DECLARE
    schema_record RECORD;
BEGIN
    -- Loop through all schemas excluding system schemas
    FOR schema_record IN
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
    LOOP
        -- Grant USAGE on the schema to pgdba
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO pgdba;', schema_record.schema_name);
    END LOOP;
END
$$;




-- Replace 'your_username' with the actual username
DO $$
DECLARE
    schema_record RECORD;
BEGIN
    -- Loop through all schemas excluding system schemas
    FOR schema_record IN
        SELECT schema_name
        FROM information_schema.schemata
        WHERE schema_name NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
    LOOP
        -- Alter default privileges for new objects created by 'your_username'
        EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE your_username IN SCHEMA %I GRANT USAGE ON SEQUENCES TO pgdba;', schema_record.schema_name);
        EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE your_username IN SCHEMA %I GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pgdba;', schema_record.schema_name);
        EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE your_username IN SCHEMA %I GRANT EXECUTE ON FUNCTIONS TO pgdba;', schema_record.schema_name);
    END LOOP;
END
$$;


-- Any new table created by the postgres role in the sdedba schema will automatically grant SELECT, INSERT, UPDATE, and DELETE privileges to the pgdba role
EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA %I GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pgdba;', 'sdedba');



CDSDBA.CDS_INTEGRATION_LOG_M



-- ALTER DEFAULT PRIVILEGES IN SCHEMA sdedba GRANT USAGE ON SEQUENCES TO pgdba;

ALTER DEFAULT PRIVILEGES IN SCHEMA sdedba GRANT SELECT, UPDATE ON SEQUENCES TO pgdba;




ALTER DEFAULT PRIVILEGES IN SCHEMA sdedba GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pgdba;

ALTER DEFAULT PRIVILEGES IN SCHEMA sdedba GRANT EXECUTE ON FUNCTIONS TO pgdba;