DECLARE 
NFOUND NUMBER;
BEGIN
    SELECT COUNT(*) INTO NFOUND FROM ALL_TAB_COLUMNS 
    WHERE TABLE_NAME = 'REF_CUST_PARTY_IDENTIFICATION' 
    AND OWNER = 'SDEDBA' 
    AND COLUMN_NAME = 'ISSUE_PLACE_NAME';
    IF NFOUND = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SDEDBA.REF_CUST_PARTY_IDENTIFICATION ADD ISSUE_PLACE_NAME VARCHAR2(200 CHAR)';
    END IF;
END;
/


-------------------



DECLARE 
NFOUND NUMBER;
BEGIN
    SELECT COUNT(*) INTO NFOUND FROM ALL_TAB_COLUMNS 
    WHERE TABLE_NAME = 'REF_CUSTOMER_TRANSACTION_TYPE' 
    AND OWNER = 'SDEDBA' 
    AND COLUMN_NAME = 'TECH_HAS_STR_EXEMPTION';
    IF NFOUND = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SDEDBA.REF_CUSTOMER_TRANSACTION_TYPE ADD TECH_HAS_STR_EXEMPTION VARCHAR2(1) DEFAULT ''0'' NOT NULL';
    END IF;
END;
/
