alter table HRDBA.HR_PERSON add TMP_PERSON_FNAME_ML VARCHAR2(200 CHAR);
Update HRDBA.HR_PERSON set TMP_PERSON_FNAME_ML=PERSON_FNAME_ML;
commit;
alter table HRDBA.HR_PERSON drop column PERSON_FNAME_ML;
alter table HRDBA.HR_PERSON rename column TMP_PERSON_FNAME_ML to PERSON_FNAME_ML; 


