DECLARE
    NFOUND NUMBER;
BEGIN
    SELECT COUNT(*) INTO NFOUND FROM SDEDBA.REF_SYS_LINES WHERE HEA_CODE = 426 AND LIN_CODE = 18;
    
    IF NFOUND = 0 THEN 
        INSERT INTO SDEDBA.REF_SYS_LINES (HEA_CODE, LIN_CODE, LIN_NAME, LIN_NAME2)
        VALUES (426, 18, 'Phone Number', 'Phone number');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Header in use');
    END IF;
END;