/*
TABLE NAME	COLUMN NAME	DATA TYPE	DATA NULL	DATA NULL
REF_OSE_COMPANY	IS_LIFE_INSURANCE	VARCHAR2(1)	N	0
*/

DECLARE 
NFOUND NUMBER;
BEGIN
    SELECT COUNT(*) INTO NFOUND FROM ALL_TAB_COLUMNS 
    WHERE TABLE_NAME = 'REF_OSE_COMPANY' 
    AND OWNER = 'SDEDBA' 
    AND COLUMN_NAME = 'IS_LIFE_INSURANCE';
    IF NFOUND = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE SDEDBA.REF_OSE_COMPANY ADD IS_LIFE_INSURANCE VARCHAR2(1) DEFAULT ''0'' NOT NULL';
    END IF;
END;
/
